post_install do |installer|
    installer.pods_project.targets.each do |target|
        target 'HuaZang' do
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
                config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
            end
        end
#        target 'NotificationService' do
#            target.build_configurations.each do |config|
#                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#            end
#        end

    end
end

# 忽略引入库的所有警告
inhibit_all_warnings!

def hzpods
    platform :ios, '9.0'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'ReactiveObjC'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'BaiduMobStatCodeless'
end

target 'HuaZangBook' do
hzpods
end


